/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedTrainingsIndexRouteImport } from './routes/_authenticated/trainings/index'
import { Route as AuthenticatedPlayersIndexRouteImport } from './routes/_authenticated/players/index'
import { Route as AuthenticatedMatchesIndexRouteImport } from './routes/_authenticated/matches/index'
import { Route as AuthenticatedTrainingsTrainingIdRouteImport } from './routes/_authenticated/trainings/$trainingId'
import { Route as AuthenticatedPlayersPlayerIdRouteImport } from './routes/_authenticated/players/$playerId'
import { Route as AuthenticatedMatchesMatchIdRouteImport } from './routes/_authenticated/matches/$matchId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTrainingsIndexRoute =
  AuthenticatedTrainingsIndexRouteImport.update({
    id: '/trainings/',
    path: '/trainings/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPlayersIndexRoute =
  AuthenticatedPlayersIndexRouteImport.update({
    id: '/players/',
    path: '/players/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMatchesIndexRoute =
  AuthenticatedMatchesIndexRouteImport.update({
    id: '/matches/',
    path: '/matches/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTrainingsTrainingIdRoute =
  AuthenticatedTrainingsTrainingIdRouteImport.update({
    id: '/trainings/$trainingId',
    path: '/trainings/$trainingId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPlayersPlayerIdRoute =
  AuthenticatedPlayersPlayerIdRouteImport.update({
    id: '/players/$playerId',
    path: '/players/$playerId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMatchesMatchIdRoute =
  AuthenticatedMatchesMatchIdRouteImport.update({
    id: '/matches/$matchId',
    path: '/matches/$matchId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/matches/$matchId': typeof AuthenticatedMatchesMatchIdRoute
  '/players/$playerId': typeof AuthenticatedPlayersPlayerIdRoute
  '/trainings/$trainingId': typeof AuthenticatedTrainingsTrainingIdRoute
  '/matches/': typeof AuthenticatedMatchesIndexRoute
  '/players/': typeof AuthenticatedPlayersIndexRoute
  '/trainings/': typeof AuthenticatedTrainingsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/': typeof AuthenticatedIndexRoute
  '/matches/$matchId': typeof AuthenticatedMatchesMatchIdRoute
  '/players/$playerId': typeof AuthenticatedPlayersPlayerIdRoute
  '/trainings/$trainingId': typeof AuthenticatedTrainingsTrainingIdRoute
  '/matches': typeof AuthenticatedMatchesIndexRoute
  '/players': typeof AuthenticatedPlayersIndexRoute
  '/trainings': typeof AuthenticatedTrainingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/matches/$matchId': typeof AuthenticatedMatchesMatchIdRoute
  '/_authenticated/players/$playerId': typeof AuthenticatedPlayersPlayerIdRoute
  '/_authenticated/trainings/$trainingId': typeof AuthenticatedTrainingsTrainingIdRoute
  '/_authenticated/matches/': typeof AuthenticatedMatchesIndexRoute
  '/_authenticated/players/': typeof AuthenticatedPlayersIndexRoute
  '/_authenticated/trainings/': typeof AuthenticatedTrainingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/settings'
    | '/matches/$matchId'
    | '/players/$playerId'
    | '/trainings/$trainingId'
    | '/matches/'
    | '/players/'
    | '/trainings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/settings'
    | '/'
    | '/matches/$matchId'
    | '/players/$playerId'
    | '/trainings/$trainingId'
    | '/matches'
    | '/players'
    | '/trainings'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/settings'
    | '/_authenticated/'
    | '/_authenticated/matches/$matchId'
    | '/_authenticated/players/$playerId'
    | '/_authenticated/trainings/$trainingId'
    | '/_authenticated/matches/'
    | '/_authenticated/players/'
    | '/_authenticated/trainings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/trainings/': {
      id: '/_authenticated/trainings/'
      path: '/trainings'
      fullPath: '/trainings/'
      preLoaderRoute: typeof AuthenticatedTrainingsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/players/': {
      id: '/_authenticated/players/'
      path: '/players'
      fullPath: '/players/'
      preLoaderRoute: typeof AuthenticatedPlayersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/matches/': {
      id: '/_authenticated/matches/'
      path: '/matches'
      fullPath: '/matches/'
      preLoaderRoute: typeof AuthenticatedMatchesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/trainings/$trainingId': {
      id: '/_authenticated/trainings/$trainingId'
      path: '/trainings/$trainingId'
      fullPath: '/trainings/$trainingId'
      preLoaderRoute: typeof AuthenticatedTrainingsTrainingIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/players/$playerId': {
      id: '/_authenticated/players/$playerId'
      path: '/players/$playerId'
      fullPath: '/players/$playerId'
      preLoaderRoute: typeof AuthenticatedPlayersPlayerIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/matches/$matchId': {
      id: '/_authenticated/matches/$matchId'
      path: '/matches/$matchId'
      fullPath: '/matches/$matchId'
      preLoaderRoute: typeof AuthenticatedMatchesMatchIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedMatchesMatchIdRoute: typeof AuthenticatedMatchesMatchIdRoute
  AuthenticatedPlayersPlayerIdRoute: typeof AuthenticatedPlayersPlayerIdRoute
  AuthenticatedTrainingsTrainingIdRoute: typeof AuthenticatedTrainingsTrainingIdRoute
  AuthenticatedMatchesIndexRoute: typeof AuthenticatedMatchesIndexRoute
  AuthenticatedPlayersIndexRoute: typeof AuthenticatedPlayersIndexRoute
  AuthenticatedTrainingsIndexRoute: typeof AuthenticatedTrainingsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedMatchesMatchIdRoute: AuthenticatedMatchesMatchIdRoute,
  AuthenticatedPlayersPlayerIdRoute: AuthenticatedPlayersPlayerIdRoute,
  AuthenticatedTrainingsTrainingIdRoute: AuthenticatedTrainingsTrainingIdRoute,
  AuthenticatedMatchesIndexRoute: AuthenticatedMatchesIndexRoute,
  AuthenticatedPlayersIndexRoute: AuthenticatedPlayersIndexRoute,
  AuthenticatedTrainingsIndexRoute: AuthenticatedTrainingsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
